# Generated by Django 3.0.2 on 2020-01-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('genero', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('NB', 'Não Binário'), ('T', 'Trans')], max_length=3)),
                ('endereco', models.CharField(max_length=30)),
            ],
        ),
    ]
